---
title: "Peaks and Primes"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Prelude 
With Olympic Games occurring once every 4 years, athletes have a limited window of opportunity to participate. 
**David Awosoga** and **Matthew Chow** analyze historical performance data in athletics to understand athlete progressions and the factors that impact the size and timing of peak performance windows.

### Bios
*David Awosoga* is a graduate student at the University of Waterloo researching sports analytics and Bayesian spatiotemporal data analysis.

<!-- insert photo here -->

*Matthew Chow* is an undergraduate student at the University of Waterloo interested in the application of statistical methods to physiology and the social sciences.

<!-- insert photo here -->

### Introduction
In the world of athletics, also known as “track and field”, athletes meticulously train to capture the most of their genetic potential in their specified event discipline, with the hopes of achieving success at the highest level of competition. Throughout an athlete’s career, performances generally follow a parabolic trajectory, reaching a maximum value at some point in their career and trending in the opposite direction for the remainder of it. This is known as a “peak” - the time interval at which an athlete achieves their lifetime best performances. The length of this interval, commonly referred to as an athlete’s “prime”, illustrates how long a peak is achievable for. This length is incredibly variable and context dependent, but in the world of athletics and competitive sport in general, an athlete’s peak is [constrained almost exclusively by their age](https://www.cairn.info/revue-gerontologie-et-societe-2012-5-page-41.htm). Therefore, an athlete’s success is not only constrained by their level of technical maturity in an event, but also by the age at which they reach the level of expertise necessary to compete with the world’s best. This has massive implications for track and field athletes in particular, as the Olympics serve as their largest stage of global competition, but only occur once every 4 years.

### You (may) Only Get One Shot
In fact, according to [data extracted from Olympedia.org](https://github.com/chanronnie/Olympics/tree/main), since the first Olympics in 1896, 71% of athletics competitors have participated in one Games, and only 8% have competed in more than 2 Games (not accounting for active athletes who have made one Games and can still qualify for more in the future). Therefore, understanding the terminal window of this progression can provide valuable information to optimize training regimes and maximize an athlete’s opportunity to qualify. Additionally, a deep dive into the physiological and event-specific patterns in athletes validates some intuition and challenges other underlying assumptions about their contributing implications. In terms of technical maturation, the rate of performance progression in athletes over time can provide valuable context to discover the presence of systematic changes within the sport at large. However, performance isn’t the only factor that determines an athlete’s ability to compete at an Olympic Games, and there are other external constraints that must be considered.

For the Paris 2024 Olympics, half of the total qualification places are reserved for athletes who achieve their events’ entry standard, a predetermined performance threshold based loosely on the marks achieved by previous finalists. These standards are intended to be quite steep, such as a 2 hours and 8 minute requirement in the men’s Marathon and a 4 minute and 21 second Mile equivalent standard in the women’s 1500m. Unfortunately, achieving a qualification standard does not guarantee participation, as each National Olympic Committee (NOC) is permitted to send a maximum of 3 participants for individual events, and 1 relay team per event. Therefore, NOCs with more than 3 athletes who achieve a qualification standard must devise other ways to determine which will actually be sent to the Olympics, and many host a National Championships Meet before the Olympics for this reason. The other half of Olympic qualifying places are awarded via a points-based rankings system. Additional considerations for athlete participants are made for the host country, and nominations can be put forward by NOCs with no individually qualified athlete or relay team. There is also a system to redistribute whatever unused quota places remain, and alternate athletes for relay teams may also receive consideration. Therefore, although there has been an increase in event offerings, the total number of participating athletes has remained relatively unchanged since 1996.

### Data
The data for this analysis comes courtesy of [World Athletics ](https://worldathletics.org), the world governing authority for athletics. Complete event results from the past 7 Olympic games - from Atlanta 1996 to Tokyo 2020 - were acquired and paired with individual career progression data for every athlete who has competed during this span. Career progression is defined as the top performances of an athlete in an event discipline from year to year throughout their career. This comprehensive data set was then curated to identify and extract key factors and appropriately scale performances. This is important because for Track events, one where the outcome is timed, lower is better, while for Field events, performances of larger magnitudes are preferred. For convenience, athletes who competed in multiple individual events were separated into independent observations. The analysis in this work was performed using various packages from the [R programming language](https://www.r-project.org) and is completely reproducible, with source code located at [https://bit.ly/3JTBlK5](https://bit.ly/3JTBlK5).
 
### A Matter of Survival
Now that we are warmed up, we can go into more detail about the main engine used to investigate an athlete’s peak window in this work - survival analysis. As can also be inferred by its name, survival analysis originated in studies of mortality among different demographics. Its applications have since been generalized to study terminal events and the time until that event takes place. In medical contexts, for example, survival analysis is used to compare the observed time to cure a disease in clinical trials between different treatments, and in industry, as the time until a specific machinery component fails. Our question is framed as “time until an athlete peaks”, where time is measured in years - the athlete’s age. A key feature that distinguishes survival analysis from other methods is that the event of interest is not guaranteed to be observed in every entity when a study is completed. Therefore, special techniques are utilized to appropriately account for these types of observations. In our situation, an athlete’s peak cannot be definitively identified until their career has come to an end, so the active athletes in this data set are **censored** - given a special label to acknowledge their status. Since it is unfeasible to manually validate the competing status of each athlete, a `RETIRED` label is given to athletes who do not have a recorded performance after December 31, 2022. This definition falls short in edge cases where an athlete takes extended time off due to childbirth, a major injury, or to serve a suspension, for example, but the proportion of such athletes is likely miniscule. 

### Babe Wake Up, it's an Olympic Year
It has been demonstrated that the ages of athletes at the Olympics in other sports such as [gymnastics](https://themedalcount.com/2020/01/18/a-history-of-the-average-age-in-womens-gymnastics/) have experienced noticeable changes over time. However, things have been remarkably consistent over the past 25 years in athletics, where the average age of just under 27 years old has displayed just 2 months of variation between Games. The lone notable exception to this trend was Tokyo 2020, where the mean age of 27.6 years old is readily explained away by the 1 year delay of the Games due to the Covid-19 pandemic. The overall mean ages are surprisingly similar between men and women as well (26.9 years old), though the median age of women is slightly higher (27 to 26). Finalists were on average 16 months older than the average participant, but medalists were only 1 month older than average. The standout example here was the 2008 Beijing Olympics, which recorded the lowest average medalist age of 26.1 years old. It is no coincidence that medalists from this Games included then-young track legends Usain Bolt (22 years old), Shelly-Ann Fraser-Pryce (22 years old), and Allyson Felix (23 years old).

Median values are typically used in place of averages in survival analysis because censored data are usually not normally distributed. From the observed data, the median peak age is 27 years old, and this is illustrated visually via a simple **Kaplan-Meier** curve*, where the probability of an athlete peaking dips under 50% for the first time after they turn 27. The uncertainty estimates of these predictions are less than +/- 1% on average and can be viewed within the magnified portion of the visualization below. 

<!-- insert graph 1 here -->

This result is both unsurprising and remarkable, as it implies that Olympic athletes are typically in their prime when they compete. In fact, we see some indications of a relationship between the relative peaks in athlete performance and the years of Olympic Games, as the difference between an athlete’s proximity from their career best in Olympic years versus non Olympic years is statistically significant. Although we have neither established the methodology necessary for appropriate causal analysis nor considered other factors such as injuries and World Championships, these preliminary results match our intuition about the incentive that the Games provide. A contemporary example of this phenomena is Tokyo 2020 Olympic Champion Andre DeGrasse, whose performance in the 200m dash seems to follow a cyclical pattern in line with the occurrence of Olympic Games.

<!-- insert graph 2 here -->

### Predicting the Peak
Unlike similar analyses that investigate athlete peaks from the lens of [summary statistics](https://cepar.edu.au/sites/default/files/peak-performance-age-sport.pdf) and their [confidence intervals](https://air.unimi.it/bitstream/2434/655133/2/1-s2.0-S1440244018305565-main%20%281%29.pdf), our approach allows us to build a model to identify certain factors that might predict an athlete’s peak. A simple set of features was used in our final model, namely `gender`,  `nationality`, `event type` , a binary `olympic year` variable, and `training age`. Training age is estimated as the number of years that an athlete has recorded an event performance at a World Athletics-sanctioned meet. The rationale behind its inclusion is to try and capture the level of technical experience that an athlete has in their event. This allows for differentiation between “late bloomers” (older athletes with a small training age) and “child prodigies” (younger athletes with a large training age). The selected model was an **oblique random survival forest**, which is an ensemble machine learning technique for [modeling censored data](https://www.tandfonline.com/doi/full/10.1080/10618600.2023.2231048).

<!-- insert graph 3 here -->

Now, we can analyze the contribution of each feature to the model via its **variable importance**, which in this context is the proportion of times that a variable has a statistically significant p-value when used in predictions. We see that `training age` is the most useful predictor of an athlete’s peak from our feature set. This could be explained partially by the fact that it demonstrates some correlation with actual age, but also matches our intuition that “experience” does help predict peaks. `Event category` has the second-highest relative influence, and its overall score is computed as the average of the magnitudes from its subcategories. Here, we see that the peaks of road racers are the “easiest” to predict, while the peaks of throwers are the most difficult. We hypothesize that the trend of older peaks in road racers improves the accuracy of model predictions, while finding out that Olympic throwers in our data set average the longest careers out of any event type may explain why peak age prediction is increasingly challenging for that event. The relative importance of `nationality` comes as a bit of a surprise, though we speculate that it requires further decomposition in order to make inferences on its various subcomponents. `Gender` has the second smallest variable importance of the feature set, and the predicted differences in example tests is quite small. Finally, we find evidence that knowledge of an `Olympic year` does indeed help predict if an athlete will peak, though this is by far the least impactful piece of information provided.

### The Curious Case of Kim Collins
Differences between predicted values and the realized data can be interpreted in terms of athletes who peak earlier or later than expected, which serves as an interesting case study. However, there is a lot of noise near the extreme values of this continuum, likely confounded by the unconventional means by which many of the identified athletes were selected for an Olympic Games. Filtering out this noise unearths a remarkable outlier, 5-time Olympian Kim Collins of St. Kitts and Nevis. The 2003 World Champion’s personal best in the 100m of 9.93 seconds came at age 40, a whopping 12 years after his predicted peak age of 28. This is tied for the second-oldest peak among non-road racers in the entire data set, trailing only Oleksandr Dryhol’s 79.42m hammer throw at the age of 46 - a mark set a few months before a retroactive ban from London 2012 for prohibited substance use. One thing to consider, however, is that the average retirement age for athletes in our data set is 32 years old. While this speaks volumes to Collins’ longevity, it also means that his peak is only comparable to a small subset of eligible athletes who were active at similar ages. Nevertheless, Collins’ career progression is particularly noteworthy because he seemingly experienced two primes, one between 2002 and 2005 (ages 26-29), and another from 2013 to 2016 (ages 37-40). In fact, each of Collins’ 4 best seasons came during the window of his “second prime”, as shown in the image below.

<!-- insert graph 4 here -->

### Conclusion
By leveraging survival analysis, we were able to make meaningful predictions about the age at which Olympic track and field athletes peak. We also find that the prime of a track and field athlete typically spans a single Olympic games, though some athletes such as Kim Collins seem to have experienced multiple windows. We found that the training age of an athlete was the most influential predictor of peak age, while the timing of the Olympics and the athlete’s nationality, event category, gender were less informative. This analysis is far from complete, and multiple areas for improvement have been identified. Firstly, including an additional feature to capture how an athlete qualifies for the Olympic Games, such as a proxy for the relative depth of an athlete’s NOC or their proximity to entry standards, could be incredibly valuable. Additionally, implementing a more rigorous methodological treatment to athletes who compete in multiple individual events may remove bias from the model. Further analysis on the rate of progression leading up to and following an athlete’s peak is another interesting extension of this work that could be used to identify athletes who have a slow and steady progression versus a sharp ascension followed by a rapid decline. By investigating these physiological and external factors, we gain a greater appreciation for the uphill battle that athletes face as they prepare themselves for what will most likely be their only chance at attaining Olympic glory.

### Acknowledgement
This work was made possible through collaboration within the University of Waterloo Analytics Group for Games and Sports (UWAGGS). A special thank you to member Rithika Silva for his extensive support acquiring the data.